name: Gator Verify All Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gator-verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        engine: [ "rego" ]
        gatekeeper: [ "3.15.1", "3.16.3" ]

    name: "Verify assertions in suite.yaml files for ${{ matrix.engine }} policies"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18' # Ensure this is the correct version or specify the latest version

      - name: Install Gator
        run: |
          go install github.com/open-policy-agent/gatekeeper/v3/cmd/gator@master
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH

      - name: Find suite.yaml files
        id: find_files
        run: |
          files=$(find policy/test -name "suite.yaml")
          echo "::set-output name=files::$files"

      - name: Run gator verify
        run: |
          for file in ${{ steps.find_files.outputs.files }}; do
            gator verify --engine=${{ matrix.engine }} --gatekeeper=${{ matrix.gatekeeper }} $file || exit 1
          done
