name: Gator Verify All Suites

on:
  push:
    branches:
      - main
    paths:
      - 'policy/**'
      - '.github/workflows/run-gator.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'policy/**'
      - '.github/workflows/run-gator.yml'

jobs:
  gator-verify:
    runs-on: ubuntu-latest
    name: "Verify assertions in suite.yaml files for ${{ matrix.engine }} policies"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Ensure this is the correct version or specify the latest version

      - name: Install Gator
        run: |
          go install github.com/open-policy-agent/gatekeeper/v3/cmd/gator@master
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH

      - name: Find suite.yaml files
        id: find_files
        run: |
          files=$(find policy/test -name "suite.yaml" | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_ENV

      - name: Print found suite.yaml files for debugging
        run: |
          echo "Found suite.yaml files: ${{ env.files }}"

      - name: Run gator verify
        run: |
          for file in ${{ env.files }}; do
            echo "Running gator verify on $file"
            gator verify $file || exit 1
          done
